### ISSUE TITLE
Texty

### ISSUE THREAD

**Issue by Krejdom** [zverinec/poznej-fi-web#1]
1/ "18.–19. 2. 2016, čtvrtek–pátek" >> s pomlčkou (ne spojovníkem) a bez mezer

2/ "Začátek programu bude ve čtvrtek přibližně v 10:00, konec v pátek zhruba v 17:00." >> doplnit předložky

3/ "PřihlaŠování bude spuštěno" >> š, ne s

**Comment by mukrop** [comment]
Fixed.
